### ISSUE TITLE
使用插件后，下面sql后报空指针异常

### ISSUE THREAD

**Issue by wangshicon** [yidasanqian/dynamic-add-date#7]
![SQL语句](https://user-images.githubusercontent.com/30708635/60700570-f33fd380-9f2a-11e9-8b32-99fa83a50771.png)

![报错信息](https://user-images.githubusercontent.com/30708635/60700534-d5726e80-9f2a-11e9-9d4a-49cf9b484cbe.png)

**Comment by yidasanqian** [comment]
你可以升级到1.1.0版本或者配置忽略表功能
